### ISSUE TITLE
Thanks for the note on Nodemon

### ISSUE THREAD

**Issue by bitsoflogic** [jedwards1211/flow-watch#23]
I've been using `nodemon` for a ton over the years, so I was glad when I saw you refer to it. Since it might not be clear how to set it up, I thought I'd share my approach in case anyone would prefer it:

In `package.json`:
```
"scripts": {
  "flow": "nodemon --exec ./flow-clean-exit.sh"
}
```

Create `./flow-clean-exit.sh` (In the root of your project):
```
#!/bin/bash

clear # Clear the terminal

# Trap, so `nodemon` will continue to work when flow encounters an error
# Otherwise, `flow` changes the process exit code and `nodemon` crashes
trap './node_modules/.bin/flow' EXIT
```

Run `chmod +x ./flow-clean-exit.sh` to give it permission to run.

And you're done.

`npm run flow` and you'll launch this service that'll watch for changes and rerun flow.

**Comment by jedwards1211** [comment]
Sorry for the delay, thanks for sharing this.  I was curious if there are simpler ways to do this with `nodemon` that don't require creating a separate script file, and I think I've found some looking at the FAQ.

You can clear the console on restart with this nodemon option ([FAQ](https://github.com/remy/nodemon/blob/master/faq.md#how-to-clear-the-console-on-restart)):

```json
{
  "events": {
    "start": "cls || clear"
  }
}
```

And then [this FAQ](https://github.com/remy/nodemon/blob/master/faq.md#error-process-failed-unhandled-exit-code-2) advises to suppress the error like so:

```
nodemon -x 'flow || exit 1'
```

I'm going to close this since there's nothing actionable but feel free to discuss this approach I shared.

**Comment by jedwards1211** [comment]
I added an example of how to get the approach I described working to https://github.com/jedwards1211/flow-watch/blob/master/README.md#you-may-not-need-this
